# -*- coding: utf-8 -*-
"""Cluster_sentences_by_similarity_Brendan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjI1684YwAXZuj5W7UBvl8W23cq9zExk

# Make up some data

Here are some sentences I created that obviously fall into certain themes, which we will test with clustering by similiarity.
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/CS399/pulsewear_sentiment_data.csv')

sentences = data['feedback_text']
sentences

"""# Compute sentence embeddings

Import a sentence transformers model from HuggingFace and compute the embedding of every sentence into whatever vector space that model uses.  This is a necessary precursor to computing the similarities, because those computations (maybe with cosine similarity??) take place in that embedding space.
"""

!pip install sentence-transformers
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
embeddings = model.encode(sentences)
embeddings

"""# Compute the similarities

Use the same model to compute similarities between every two sentences, now that we have them stored as embeddings.  We'll put it in a pandas dataframe for readability, but later we'll just need the numbers inside, not the row/col headings.
"""

import pandas as pd
df = pd.DataFrame(model.similarity(embeddings, embeddings), columns=sentences, index=sentences)
df

"""# Useful reference

I got [advice from Claude](https://claude.ai/share/e3ae1af7-328e-4b0e-94f0-fcc7db170623) on the specific sklearn clustering code to use when you have a similarity matrix.  Below, I just attempt the first of the techniques Claude suggested, which works pretty well in this experiment.

# Turn similarities into distances

This is just a one-minus operation, because similarity is "closeness" and distance is "farness" so we need to turn it around.  Note that in some rare cases (when the similarity score of 1.0 wasn't exactly 1.0, but just very close to it within machine precision), we get 1.0 minus similarity to be a tiny negative number, which we therefore round up to zero, so the clustering algorithm won't yell at us about negative distances.
"""

import numpy as np
distances = (1 - df).to_numpy() # drop row/col headings, keep just the #s
distances = np.clip(distances, 0.0, None) # round up to zero if there were machine precision errors (tiny negative #s)
distances.min(), distances.max()

"""# Make function for clustering experiments

Here's a function that does the clustering and reports on it.  It also stores the goodness metric into a global array so we can make an elbow plot later.
"""

import sklearn as sk

def try_n_clusters(n):

    #global data_for_elbow_plot
    model = sk.cluster.AgglomerativeClustering(n_clusters=n, metric='precomputed', linkage='average')
    labels = model.fit_predict(distances)
    score = sk.metrics.silhouette_score(distances,labels,metric='precomputed')

    #data_for_elbow_plot.append((n,score))
    print('\n# clusters: ',n)
    print('Silhouette score: ',score)

    for cluster_index in range(n):
        cluster_sentences = [ sentence for (index,sentence) in enumerate(sentences) if labels[index] == cluster_index ]
        print('Cluster',cluster_index)

        # Only print a few examples to avoid excessive output
        for i, sentence in enumerate(cluster_sentences[:5]): # Print up to 5 sentences per cluster
            print('\t'+sentence)
        if len(cluster_sentences) > 5:
            print(f'\t... ({len(cluster_sentences) - 5} more sentences)')
    return labels

cluster_labels = try_n_clusters(10)
print(f"\nShape of cluster_labels: {cluster_labels.shape}")

data['cluster_label'] = cluster_labels
data.head()

grouped_sentences = data.groupby('cluster_label')['feedback_text'].apply(list)
for cluster_id, sentences_in_cluster in grouped_sentences.items():
    print(f"\nCluster {cluster_id}:")
    for i, sentence in enumerate(sentences_in_cluster[:5]): # Print up to 5 sentences for each cluster
        print(f"\t- {sentence}")
    if len(sentences_in_cluster) > 5:
        print(f"\t... ({len(sentences_in_cluster) - 5} more sentences)")

!pip install google-generativeai
import google.generativeai as genai
import google.colab.userdata
import time

genai.configure(api_key=google.colab.userdata.get('GOOGLE_API_KEY'))

# Initialize the model with 'gemini-flash-latest', as 'gemini-pro-latest' encountered quota issues
model = genai.GenerativeModel('gemini-flash-latest')

print("Gemini API configured and model initialized with 'gemini-flash-latest'.")

def generate_gemini_label(sample_sentences):
    prompt = f"Given the following sentences, generate a concise, descriptive label (once sentence) that captures the main theme of these sentences. Do not use any introductory phrases like 'The theme is' or 'This cluster is about'.\n\nSentences:\n{'; '.join(sample_sentences)}\n\nLabel:"

    retries = 3
    delay = 5  # seconds
    for i in range(retries):
        try:
            response = model.generate_content(prompt)
            # Extract the text from the response, handling potential empty responses
            try:
                label = response.candidates[0].content.parts[0].text.strip()
            except (AttributeError, IndexError):
                label = "" # Return empty string if no content is found
            break # Break loop if successful
        except Exception as e: # Catch a broader exception for safety, but specifically target TooManyRequests
            if "TooManyRequests" in str(e) and i < retries - 1:
                print(f"Quota exceeded, retrying in {delay} seconds...")
                time.sleep(delay)
                delay *= 2 # Exponential backoff
            else:
                print(f"Error generating label after {i+1} attempts: {e}")
                label = "" # Return empty string on persistent error
                break

    # Ensure the label is concise (max 5 words)
    # label_words = label.split()
    # if len(label_words) > 5:
    #     label = ' '.join(label_words[:5])

    return label

print("Function 'generate_gemini_label' redefined with retry logic.")

cluster_id_to_description = {}
for cluster_id, sentences_in_cluster in grouped_sentences.items():
    # Take a sample of sentences for generating the label
    # Using a larger sample (e.g., first 10-20 sentences) might give a better description
    sample_for_label = sentences_in_cluster[:10] # Using first 10 sentences as a sample
    description = generate_gemini_label(sample_for_label)
    cluster_id_to_description[cluster_id] = description

# Map the generated descriptions back to the original DataFrame
data['cluster_description'] = data['cluster_label'].map(cluster_id_to_description)

print("Generated cluster descriptions:")
for cluster_id, description in cluster_id_to_description.items():
    print(f"Cluster {cluster_id}: {description}")

data.head()

data.to_csv('/content/drive/MyDrive/Colab_Notebooks/CS399/pulsewear_clustered_data.csv')