# -*- coding: utf-8 -*-
"""Sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubDTsHYeH-YJ9gMt4BWALSl28EgfnV-U

# Importing and using a simple AI model

This model is *not* a chat bot.  It analyzes text and tells you whether the sentiment in that text is positive or negative.  It accompanies that binary response with a confidence score (0.0 = no confidence, 1.0 = totally confident).

This example shows:

 1. It is easy to import an AI model from HuggingFace.  You don't even have to choose the exact model; you can just choose the task and let it pick a commonly-used model for you.
 1. Not all AI models are chatbots.
"""

# Import the HuggingFace transformers library:
from transformers import pipeline

# Download and install a sentiment analysis model:
model = pipeline("sentiment-analysis")

# Notice the progress bars shown below as the model is downloaded...

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/CS399/pulsewear_feedback_data.csv')

sentiment_results = model(data['feedback_text'].tolist())

data['sentiment_label'] = [result['label'] for result in sentiment_results]
data['sentiment_score'] = [result['score'] for result in sentiment_results]

display(data.head())

data.to_csv('/content/drive/MyDrive/Colab_Notebooks/CS399/pulsewear_sentiment_data.csv')