// ============================================================
// PulseWear Labs — Data (sourced from pre-exported JSON files)
// JSON files generated by backend/export_to_json.py from
// data generation excel/Data/pulsewear_clustered_data.csv
// ============================================================

import themesRaw   from './themes.json';
import trendsRaw   from './trends.json';
import roadmapRaw  from './roadmap.json';
import feedbackRaw from './feedback.json';

export interface Theme {
  cluster_id: number;
  name: string;
  description: string;
  volume: number;
  positive_pct: number;
  negative_pct: number;
  avg_score?: number;
  roadmap_id: string | null;
  status?: string | null;
  priority_score: number;
}

export interface ChannelStat {
  name: string;
  count: number;
  pct: number;
}

export interface SummaryStats {
  total_feedback: number;
  positive_pct: number;
  negative_pct: number;
  active_themes: number;
}

export interface AccountProfile {
  initials: string;
  name: string;
  role: string;
  email: string;
  team: string;
  location: string;
  plan: string;
}

export interface MonthlyDataPoint {
  month: string;        // e.g. "Sep 2025"
  month_short: string;  // e.g. "Sep"
  volumes: number[];    // volume per cluster (index = cluster_id)
}

export interface RoadmapItem {
  roadmap_id: string;
  cluster_id: number;
  theme_name: string;
  volume: number;
  positive_pct: number;
  negative_pct: number;
  priority_score: number;
  status: 'Active' | 'Planned' | 'Under Review' | 'Backlog';
}

export interface FeedbackItem {
  feedback_id: string;
  text: string;
  sentiment: 'POSITIVE' | 'NEGATIVE';
  score: number;
  channel: string;
  platform: string;
  timestamp: string;
}

// ── Themes (clusters derived from CSV) ────────────────────────
export const themes: Theme[] = themesRaw as Theme[];

// ── Monthly Trend Data ─────────────────────────────────────────
export const monthlyTrends: MonthlyDataPoint[] = trendsRaw as MonthlyDataPoint[];

// ── Roadmap Items ──────────────────────────────────────────────
export const roadmapItems: RoadmapItem[] = roadmapRaw as RoadmapItem[];

// ── Sample Feedback Quotes (30 per cluster) ────────────────────
export const sampleFeedback = feedbackRaw as unknown as Record<number, FeedbackItem[]>;

// ── Summary Stats (computed from themes) ──────────────────────
const _total = themes.reduce((s, t) => s + t.volume, 0);
const _posCount = themes.reduce((s, t) => s + t.volume * (t.positive_pct / 100), 0);

export const summaryStats: SummaryStats = {
  total_feedback: _total,
  positive_pct:   Math.round(_posCount / _total * 100),
  negative_pct:   Math.round((1 - _posCount / _total) * 100),
  active_themes:  themes.length,
};

// ── Account Profile ────────────────────────────────────────────
export const accountProfile: AccountProfile = {
  initials: 'EB',
  name: 'Ethan Brooks',
  role: 'Product Insights Lead',
  email: 'ethan.brooks@pulsewearlabs.com',
  team: 'Customer Feedback Intelligence',
  location: 'Boston, MA',
  plan: 'Admin access'
};

// ── Channel Breakdown ──────────────────────────────────────────
export const channels: ChannelStat[] = [
  { name: 'App Review',     count: 5600, pct: 28 },
  { name: 'Support Ticket', count: 4800, pct: 24 },
  { name: 'Social Media',   count: 5200, pct: 26 },
  { name: 'Beta Testing',   count: 4400, pct: 22 },
];

// Helper: compute month-over-month change for a cluster
export function getTrend(clusterId: number): number {
  const n = monthlyTrends.length;
  if (n < 2) return 0;
  const last = monthlyTrends[n - 1].volumes[clusterId];
  const prev = monthlyTrends[n - 2].volumes[clusterId];
  if (prev === 0) return 0;
  return Math.round(((last - prev) / prev) * 100);
}
